### ISSUE TITLE
Sign Out - test results

### ISSUE THREAD

**Issue by chalkboard3000** [michael-munoz/WePlayCards#2]
Test results of sign out (includes logout.php, dbconnect.php, index.php and home.php)
Ignore design loyout.
This is to test integration with blackjack and sign out process flow.
Keep open until Vichaya confirms this is the expected results.

<img width="300" alt="signout link" src="https://cloud.githubusercontent.com/assets/14241478/10989854/567a9b0e-8401-11e5-94e0-e09ffef8f5c2.png"><img width="300" alt="signout test results" src="https://cloud.githubusercontent.com/assets/14241478/10989879/b1500d3e-8401-11e5-8dfd-9ad899f4dba3.png">

**Comment by VALVeisG0D** [comment]
Yep that is the way it should work: clicking sign out will take you from the current screen (In-Game or on the Main Menu) to the sign-in screen.
